#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database:  <%= ENV['RDS_DATABASE'] %>
  username:  <%= ENV['RDS_USERNAME'] %>
  password:  <%= ENV['RDS_PASSWORD'] %>
  host:      <%= ENV['EC2_DATABASE_HOST'] %>
  port:      <%= ENV['PGSQL_PORT'] %>
